#!/usr/bin/env bash
# Environment carrier :3

set -e

# Create self-deleting wrapper as `$wrapper` that calls bash with our bashrc; can be used as SHELL
function create_wrapper() {
	wrapper="$(mktemp --suffix=".envy")"
	echo '#!/bin/bash' > "$wrapper"
	echo "rm -f \"$wrapper\"" >> "$wrapper"
	echo "$script" >> "$wrapper"
	chmod +rx "$wrapper"	# make executable; and world-readable for `sudo -u luser`
}

## Arguments
case "$1" in
	ssh|sudo|su|screen) ;;
	*)
		echo "Take your environment with you through ssh|sudo|su|screen! :3" >&2
		echo "Usage: $(basename "$0") <ssh|sudo|su|screen> [args...]" >&2
		exit 1
		;;
esac

## Environment
env="$( tar cJf - -h -C "${ENV_HOME:-${XDG_CONFIG_HOME:-$HOME/.config/}/envy.d/}" -- "." | base64 )"
# `--rcfile` for interactive shells, `BASH_ENV` for non-interactive ones
script='
	set -e
	export SHELL="/bin/bash"
	export ENV_HOME="$( mktemp -d -p "${TMPDIR:-/tmp}" -t "env-$USER.XXXXXX" )"
	<<< '"'$env'"' base64 -d | tar xJf - --no-same-owner --skip-old-files -C "$ENV_HOME"
	echo ""  >> "$ENV_HOME/.bashrc"
	sed -i "1i unset BASH_ENV" "$ENV_HOME/.bashrc"
	echo "if [[ -s \"\$ENV_HOME/env_commands\" ]]; then . \"\$ENV_HOME/env_commands\"; fi" >> "$ENV_HOME/.bashrc"
	echo "trap -- \"rm -rf \\\"\$ENV_HOME\\\"\" EXIT" >> "$ENV_HOME/.bashrc"
	BASH_ENV="$ENV_HOME/.bashrc" exec bash --rcfile "$ENV_HOME/.bashrc" "$@"
'

## Business
subcmd="$1"; shift; case "$subcmd" in
	ssh)
		exec ssh -t -o RemoteCommand="${script//%/%%}" "$@"
		;;
	sudo)
		create_wrapper
		SHELL="$wrapper" exec sudo -s "$@"
		;;
	su)
		create_wrapper
		exec su -s "$wrapper" "$@"
		;;
	screen)
		# FIXME: screen needs to keep wrapper around for creating new windows (Ctrl+a, c)
		create_wrapper
		screen -s "$wrapper" -t "$(basename "$0")" "$@"
		;;
esac
rm -f "$wrapper"	# if above failed
