#!/usr/bin/env bash
# Environment carrier :3

set -e

## Configs
if [[ $ENV_HOME ]]; then
	include_dir="$ENV_HOME"
else
	include_dir="${XDG_CONFIG_HOME:-$HOME/.config/}/envy.d/"
	if ! [[ -d "$include_dir" && -n "$(ls -A "$include_dir")" ]]; then
		echo "Please put something in here first: $include_dir" >&2
		exit 2
	fi
fi

## Arguments
case "$1" in
	ssh|sudo|su) ;;
	*)
		echo "Take your environment with you through ssh|sudo|su! :3" >&2
		echo "Usage: $(basename "$0") <ssh|sudo|su> [args...]" >&2
		exit 1
		;;
esac

## Environment
env="$( tar cJf - -h -C "$include_dir" -- "." | base64 )"
# `--rcfile` for interactive shells, `BASH_ENV` for non-interactive ones
script='
	set -e
	export SHELL="/bin/bash"
	export ENV_HOME="$( mktemp -d -p "${TMPDIR:-/tmp}" -t "env-$USER.XXXXXX" )"
	<<< '"'$env'"' base64 -d | tar xJf - --no-same-owner --skip-old-files -C "$ENV_HOME"
	echo ""  >> "$ENV_HOME/.bashrc"
	echo "unset BASH_ENV" >> "$ENV_HOME/.bashrc"
	echo "if [[ -x $ENV_HOME/env_commands ]]; then . $ENV_HOME/env_commands; fi" >> "$ENV_HOME/.bashrc"
	echo "trap -- \"rm -rf \\\"\$ENV_HOME\\\"\" EXIT" >> "$ENV_HOME/.bashrc"
	BASH_ENV="$ENV_HOME/.bashrc" exec bash --rcfile "$ENV_HOME/.bashrc" "$@"
'
## Business
subcmd="$1"; shift; case "$subcmd" in
	ssh)
		exec ssh -t -o RemoteCommand="${script//%/%%}" "$@"
		;;
	sudo|su)
		cmdfile="$(mktemp --suffix=".envy")"
		echo '#!/bin/bash' > "$cmdfile"
		echo "rm -f \"$cmdfile\"" >> "$cmdfile"
		echo "$script" >> "$cmdfile"
		chmod +rx "$cmdfile"	# make executable; and world-readable for `sudo -u luser`

		if [[ "$subcmd" == "sudo" ]]; then
			SHELL="$cmdfile" exec sudo -s "$@"
		else
			exec su -s "$cmdfile" "$@"
		fi

		rm -f "$cmdfile"	# if above failed
		;;
esac
